branches:
  only:
    - master

# build config
build_script:
  - ps: .\build.ps1 -target pack

# tests config
test: off

# artifacts config
artifacts:
  - path: '.\build\artifacts\*.nupkg'

# publish artifacts config
deploy:
  - provider: NuGet
    api_key: 
      secure: z44CwwunvCyTy8Rk0BplABnNnahqkpfnS/rbHLo2uFrvFhQ7QvsR5mKkceqM/qou